# Generated by Django 5.1.2 on 2024-10-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_date_event_day_date_event_time_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
